service: extralife

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "${env:DOMAIN}"
    createRoute53Record: true
    endpointType: "regional"
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false

# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  environment:
    PARTICIPANTS_TABLE: extra-life-participants-${opt:stage, "development"}
    TEAMS_TABLE: extra-life-teams-${opt:stage, "development"}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:*"

package:
  individually: true
  patterns:
    - "!./**"
    - "./bin/**"

functions:
  update-data:
    handler: bin/update-data
    events:
      - schedule: rate(5 minutes)
      - http:
          path: update-data
          method: get
  get:
    handler: bin/get
    events:
      - http:
          path: /{participantId}
          method: get
resources:
  Resources:
    ExtraLifeParticipantsTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: participantId
            AttributeType: N
        KeySchema:
          - AttributeName: participantId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: 'extra-life-participants-${opt:stage, "development"}'
    ExtraLifeTeamsTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: teamId
            AttributeType: N
        KeySchema:
          - AttributeName: teamId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: 'extra-life-teams-${opt:stage, "development"}'
