name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use GoLang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17.1" # The Go version to download (if necessary) and use.

      - name: 📦 Build project
        run: scripts/build.sh

      # - name: 🧹 Run lint

      # - name: 🐛 Run tests

      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: -c "serverless plugin install --name serverless-domain-manager && serverless deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          DOMAIN: ${{ secrets.DOMAIN }}